### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by Harshwardhan4k** [Harshwardhan4k/Fishbook#2]

**Comment by Khusyasy** [comment]
hello, @Harshwardhan4k , can I take this issue?

**Comment by hackstar1** [comment]
Hello @Harshwardhan4k I can try going for it.

**Comment by Harshwardhan4k** [comment]
@Khusyasy @hackstar1 I have assigned the issue to both of you.

**Comment by hackstar1** [comment]
Thanks!

**Comment by Khusyasy** [comment]
thanks
